# Generated by Django 4.2.7 on 2023-12-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscrlbers',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='catalog.user'),
        ),
    ]
