# Generated by Django 4.2.7 on 2023-11-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию', max_length=100, unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг статьи')),
                ('name', models.CharField(help_text='Введите заголовок статьи / новости', max_length=100, verbose_name='Заголовок статьи / новости')),
                ('title', models.TextField(blank=True, help_text='Текст статьи / новости', max_length=1000, verbose_name='Текст статьи / новости')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(choices=[('NT', 'Новость'), ('AR', 'Статья')], default='NT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категорию', through='catalog.PostCategory', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, help_text='Текст комментария', max_length=1000, verbose_name='Комментарий')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг комментария')),
                ('post', models.ForeignKey(help_text='Выберите новость/статью для комментария', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.post', verbose_name='Выбор новости/статьи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Выберите автора новости/статьи', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Автор новости/статьи'),
        ),
    ]
